
SELECT 'TMD_ITEMS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ITEMS t
WHERE t.ITEM = :p_item_code
UNION ALL
SELECT 'IL_TMD_ITEMS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ITEMS il
WHERE il.ITEM = :p_item_code -- Assumendo che IL_TMD_ITEMS abbia anche una colonna ITEM

SELECT 'TTR_ITEMS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TTR_ITEMS t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION all
SELECT 'IL_TTR_ITEMS' AS table_name, 'COPIA' AS source_type, il.*
FROM boom.IL_TTR_ITEMS il
WHERE il.ITEM_ID IN (SELECT ID FROM IL_TMD_ITEMS WHERE ITEM = :p_item_code)


SELECT 'TMD_ITEM_LOGISTICS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ITEM_LOGISTICS t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ITEM_LOGISTICS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ITEM_LOGISTICS il
WHERE il.ITEM_ID IN (SELECT ID FROM IL_TMD_ITEMS WHERE ITEM = :p_item_code)
 

SELECT 'TMD_ITEM_SALES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ITEM_SALES t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ITEM_SALES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ITEM_SALES il
WHERE il.ITEM_ID IN (SELECT ID FROM IL_TMD_ITEMS WHERE ITEM = :p_item_code)

SELECT 'TMD_LOGISTIC_UNITS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_LOGISTIC_UNITS t
WHERE t.ITEM_LOGISTIC_ID IN (SELECT ID FROM TMD_ITEM_LOGISTICS WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_LOGISTIC_UNITS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_LOGISTIC_UNITS il
WHERE il.ITEM_LOGISTIC_ID IN (SELECT ID FROM il_TMD_ITEM_LOGISTICS WHERE ITEM_ID IN (SELECT ID FROM IL_TMD_ITEMS WHERE ITEM = :p_item_code))


SELECT 'TTR_ITEM_SALES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TTR_ITEM_SALES t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TTR_ITEM_SALES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TTR_ITEM_SALES il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code))

SELECT 'TMD_SALE_PRICES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SALE_PRICES t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_SALE_PRICES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SALE_PRICES il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code))


SELECT 'TMD_SALE_PRICES_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SALE_PRICES_VAR t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_SALE_PRICES_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SALE_PRICES_VAR il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code))


SELECT 'TMD_PURCHASE_PRICES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_PURCHASE_PRICES t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_PURCHASE_PRICES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_PURCHASE_PRICES il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_PURCHASE_PRICES_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_PURCHASE_PRICES_VAR t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_PURCHASE_PRICES_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_PURCHASE_PRICES_VAR il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)


select bb.* from ( 
SELECT 'TMD_FEATURE_ITEM_LINKS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_FEATURE_ITEM_LINKS t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)  
UNION ALL
SELECT 'IL_TMD_FEATURE_ITEM_LINKS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_FEATURE_ITEM_LINKS il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)  ) bb
order by bb.specific_feature_id

SELECT 'TMD_SALEABLE_ASSORTMENTS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SALEABLE_ASSORTMENTS t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_SALEABLE_ASSORTMENTS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SALEABLE_ASSORTMENTS il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code))



SELECT 'TMD_ORDERABLE_ASSORTMENTS_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ORDERABLE_ASSORTMENTS_VAR t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ORDERABLE_ASSORTMENTS_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ORDERABLE_ASSORTMENTS_VAR il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)


SELECT 'TMD_ORDERABLE_ASSORTMENTS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ORDERABLE_ASSORTMENTS t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ORDERABLE_ASSORTMENTS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ORDERABLE_ASSORTMENTS il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)


SELECT 'TMD_SUPPLIER_ITEM_CODES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SUPPLIER_ITEM_CODES t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_SUPPLIER_ITEM_CODES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SUPPLIER_ITEM_CODES il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_STRUCTURE_ITEM_LINKS_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_STRUCTURE_ITEM_LINKS_VAR t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_STRUCTURE_ITEM_LINKS_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_STRUCTURE_ITEM_LINKS_VAR il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_STRUCTURE_ITEM_LINKS' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_STRUCTURE_ITEM_LINKS t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_STRUCTURE_ITEM_LINKS' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_STRUCTURE_ITEM_LINKS il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_ITEM_CODES_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ITEM_CODES_VAR t
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ITEM_CODES_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ITEM_CODES_VAR il
WHERE il.ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_ITEM_CODES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_ITEM_CODES t -- Tabella originale
WHERE t.ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code)
UNION ALL
SELECT 'IL_TMD_ITEM_CODE' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_ITEM_CODE il -- Tabella creata (il_tmd_item_code)
WHERE il.ITEM_ID  IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code)



SELECT 'TMD_SALE_CODES_VAR' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SALE_CODES_VAR t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_SALE_CODES_VAR' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SALE_CODES_VAR il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code))



SELECT 'TMD_SALE_CODES' AS table_name, 'ORIGINAL' AS source_type, t.*
FROM TMD_SALE_CODES t
WHERE t.ITEM_SALE_ID IN (SELECT ID FROM TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM TMD_ITEMS WHERE ITEM = :p_item_code))
UNION ALL
SELECT 'IL_TMD_SALE_CODES' AS table_name, 'COPIA' AS source_type, il.*
FROM IL_TMD_SALE_CODES il
WHERE il.ITEM_SALE_ID IN (SELECT ID FROM il_TMD_ITEM_SALES WHERE ITEM_ID IN (SELECT ID FROM il_TMD_ITEMS WHERE ITEM = :p_item_code));