-- Popolamento tabella boom.tin_data_query
-- Eseguire dopo tin_data_query_DDL.sql
-- SQL memorizzato senza newline/tab (una riga) per esecuzione da procedura

-- DELETE FROM boom.tin_data_query WHERE update_type IN ('2','3');

-- ========== update_type = '2' ==========

INSERT INTO boom.tin_data_query (update_type, ord, descrizione_step, sql, active_flag, creation_date, update_date, creation_user, last_user, transaction_code) VALUES
('2', 1, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_purchase', 'update tin_data_item_in set end_date_purchase=''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_purchase =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 2, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_structure', 'update tin_data_item_in set end_date_structure = ''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_structure =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 3, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_item_code', 'update tin_data_item_in set end_date_item_code = ''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_item_code =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 4, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_sale_code', 'update tin_data_item_in set end_date_sale_code =''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_sale_code =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 5, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_assortment', 'update tin_data_item_in set end_date_assortment=''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_assortment =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 6, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_sale', 'update tin_data_item_in set end_date_sale=''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_sale =''9999-12-31'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 7, 'Righe aggiornate TIN_DATA_ITEM_IN campo end_date_assortment (2098-11-02)', 'update tin_data_item_in set end_date_assortment = ''2099-12-31'' where source_type_pc >= 100 and source_type_pc < 200 and end_date_assortment = ''2098-11-02'' and processing_step1 = 1 and processing_step2 = 1 and processing_step3 = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 8, 'Righe aggiornate TIN_DATA_ITEM_IN campo is_variable_price', 'update TIN_DATA_ITEM_IN set is_variable_price = 0 where is_variable_price is null', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('2', 9, 'Righe aggiornate TIN_DATA_ITEM_IN campo operational_agreement', 'update tin_data_item_in tdii set operational_agreement = ''M80'' where supplier_code = ''867'' and operational_agreement = ''86701''', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', '');

-- ========== update_type = '3' ==========

INSERT INTO boom.tin_data_query (update_type, ord, descrizione_step, sql, active_flag, creation_date, update_date, creation_user, last_user, transaction_code) VALUES
('3', 1, 'Righe aggiornate TMD_ITEMS campo is_local', 'update tmd_items set is_local = 1 where item collate case_like like ''1_____-__'' and is_local = 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 2, 'Assortimenti vendibili inseriti', 'insert into tmd_saleable_assortments(item_sale_id,network_id,status_pc,last_user,transaction_code) select item_sale_id,vnd.child_network_id, 1 status_pc ,''pr_last_operations'',transaction_code from tmd_sale_prices_var tspv, vpa_networks_desc vnd where current_date between start_date and end_date and sale_price_type_pc =1 and vnd.network_id = tspv.network_id and vnd.is_stock_management = 1 and not exists (select 1 from tmd_saleable_assortments tsa where tsa.item_sale_id=tspv.item_sale_id and tsa.network_id=vnd.child_network_id)', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 3, 'Barcode di riordino per articoli locali inseriti', 'INSERT INTO tmd_sale_codes_var (item_sale_id, code_type_pc, sale_code, start_date, end_date, is_label, is_updated, transaction_code) WITH dati_preparati AS (SELECT tis.id AS item_sale_id, ti.transaction_code, split_part(ti.item COLLATE "default", ''-'', 1) AS prefisso_item, replace(ti.item COLLATE "default", ''-'', '''') AS item_senza_trattino FROM tmd_items ti INNER JOIN tmd_item_sales tis ON ti.id = tis.item_id WHERE 1=1 AND regexp_match(ti.item COLLATE "default", ''[A-Za-z]'') IS NULL AND NOT EXISTS (SELECT 1 FROM tmd_sale_codes_var tscv WHERE code_type_pc = 12 AND current_date BETWEEN start_date AND end_date AND tscv.item_sale_id = tis.id) AND EXISTS (SELECT 1 FROM tmd_feature_item_links tfil WHERE tfil.item_id = ti.id AND specific_feature_id = (SELECT id FROM tpa_specific_features WHERE specific_feature = ''MAG_RIF'') AND features_value = ''R99'')) SELECT item_sale_id, 12 AS code_type_pc, CASE WHEN length(prefisso_item) > 6 THEN ''799'' || substr(lpad(item_senza_trattino, 9, ''0''), 1, 9) || fn_get_check_digit(''799'' || lpad(item_senza_trattino, 9, ''0'')) ELSE ''7999'' || substr(lpad(item_senza_trattino, 8, ''0''), 1, 8) || fn_get_check_digit(''7999'' || lpad(item_senza_trattino, 8, ''0'')) END AS sale_code, current_date AS start_date, to_date(''31122099'', ''DDMMYYYY'') AS end_date, 0 AS is_label, 1 AS is_updated, transaction_code FROM dati_preparati', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 4, 'Righe tin_trace_in aggiornate per presenza promo', 'update tin_trace_in tti set flg_upd_promo =1 where exists (select 1 from tin_data_promotion_in td, tmd_networks tn, tmd_items ti where td.item =ti.item and tn.network_code =td.network and tti.network_id = tn.id and tti.item_id = ti.id and td.creation_date >=current_date) and tti.date_elab =current_date and flg_upd_promo =0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 5, 'Righe flag principale fornitore assortimento aggiornate', 'UPDATE TMD_ORDERABLE_ASSORTMENTS_VAR TOAV SET MAIN_SUPPLIER =1 WHERE CURRENT_DATE BETWEEN START_DATE AND END_DATE AND NOT EXISTS (SELECT * FROM TMD_ORDERABLE_ASSORTMENTS_VAR TOAV2 WHERE CURRENT_DATE BETWEEN TOAV2.START_DATE AND TOAV2.END_DATE AND TOAV2.ITEM_ID = TOAV.ITEM_ID AND TOAV2.ITEM_LOGISTIC_ID = TOAV.ITEM_LOGISTIC_ID AND TOAV2.LOGISTIC_UNIT_ID = TOAV.LOGISTIC_UNIT_ID AND TOAV2.NETWORK_ID = TOAV.NETWORK_ID AND MAIN_SUPPLIER = 1) AND ID = (SELECT MIN(TOAV2.ID) FROM TMD_ORDERABLE_ASSORTMENTS_VAR TOAV2 WHERE CURRENT_DATE BETWEEN TOAV2.START_DATE AND TOAV2.END_DATE AND TOAV2.ITEM_ID = TOAV.ITEM_ID AND TOAV2.ITEM_LOGISTIC_ID = TOAV.ITEM_LOGISTIC_ID AND TOAV2.LOGISTIC_UNIT_ID = TOAV.LOGISTIC_UNIT_ID AND TOAV2.NETWORK_ID = TOAV.NETWORK_ID) AND MAIN_SUPPLIER =0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 6, 'Inserite righe con prezzo AS400 gestiti con Multiplo/sottomultiplo', 'insert into tmd_purchase_prices_as400 (id, item_id, price, multiplo, creation_date) select t.id, ti.id,net_cost,cv_ratio,now() from (select id,item, "substring"(tin_data_item_in.buffer_str::text, 123 + 1, 1) AS cv_ratio_type, "substring"(tin_data_item_in.buffer_str::text, 124 + 1, 7)::numeric/1000 AS cv_ratio, "substring"(tin_data_item_in.buffer_str::text, 293 + 1, 8) AS start_date_list, "substring"(tin_data_item_in.buffer_str::text, 301 + 1, 8) AS end_date_list, "substring"(tin_data_item_in.buffer_str::text, 309 + 1, 11)::numeric/100 AS net_cost, creation_date FROM tin_data_item_in WHERE tin_data_item_in.source_type_pc = 10 AND tin_data_item_in.processing_step1 = 1::numeric AND tin_data_item_in.processing_step2 = 1::numeric and "substring"(tin_data_item_in.buffer_str::text, 123 + 1, 1) = ''S'' and id in (select max(id) from tin_data_item_in tdii WHERE tdii.source_type_pc in (110,10) AND tdii.processing_step1 = 1::numeric AND tdii.processing_step2 = 1::numeric and tdii.item=tin_data_item_in.item group by item) UNION all select id,item, "substring"(tin_data_item_in.buffer_str::text, 141, 1) AS cv_ratio_type, "substring"(tin_data_item_in.buffer_str::text, 142, 7)::numeric/1000 AS cv_ratio, "substring"(tin_data_item_in.buffer_str::text, 311, 8) AS start_date_list, "substring"(tin_data_item_in.buffer_str::text, 319, 8) AS end_date_list, "substring"(tin_data_item_in.buffer_str::text, 327, 11)::numeric/100 AS net_cost, creation_date FROM tin_data_item_in WHERE tin_data_item_in.source_type_pc = 110 AND tin_data_item_in.processing_step1 = 1::numeric AND tin_data_item_in.processing_step2 = 1::numeric and "substring"(tin_data_item_in.buffer_str::text, 141, 1) = ''S'' and id in (select max(id) from tin_data_item_in tdii WHERE tdii.source_type_pc in (110,10) AND tdii.processing_step1 = 1::numeric AND tdii.processing_step2 = 1::numeric and tdii.item=tin_data_item_in.item group by item)) as T, tmd_items ti where 1=1 and t.item = ti.item and t.net_cost != 0 and not exists (select * from tmd_purchase_prices_as400 a where a.id = t.id)', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 7, 'Righe flag etichetta mancante aggiornate', 'update tmd_sale_codes_var set is_label =1 where id in (select tab.id from (select row_number() OVER (PARTITION BY tscv.item_sale_id, coalesce(tscv.network_id,0) ORDER BY (case when (trim(vp.str_val_3)::varchar~ ''^-?[0-9]*.?[0-9]*$'' collate case_like) = false then ''999999'' when coalesce(trim(vp.str_val_3),''999999'')= '''' then ''999999'' else coalesce(trim(vp.str_val_3),''999999'') end)::numeric, tscv.end_date desc, tscv.start_date desc, tscv.id desc) AS priority, tscv.id from tmd_sale_codes_var tscv inner join vpa_parameters vp on vp.parameter_code = tscv.code_type_pc where current_date between start_date and end_date and is_default =1 and parameter_header =15 and num_val_5 =1 and tscv.item_sale_id = ANY( (SELECT ARRAY( select tis.id from tmd_item_sales tis where not exists (select 1 from tmd_sale_codes_var tscv where tis.id=tscv.item_sale_id and current_date between start_date and end_date and tscv.is_label=1)))::bigint[] )) as tab where tab.priority = 1 )', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 8, 'Aggiornamento Barcode di tipo F per togliere gli zeri iniziali', 'UPDATE tmd_sale_codes_var t1 SET sale_code = LTRIM(sale_code COLLATE "default", ''0'') WHERE code_type_pc IN (SELECT parameter_code FROM vpa_parameters WHERE parameter_header = ''15'' AND str_comment = ''F'') AND CURRENT_DATE BETWEEN start_date AND end_date AND (sale_code COLLATE "default") LIKE ''0%'' AND NOT EXISTS (SELECT 1 FROM tmd_sale_codes_var t2 WHERE (t2.sale_code COLLATE "default") = LTRIM(t1.sale_code COLLATE "default", ''0'') AND t2.item_sale_id = t1.item_sale_id AND t2.code_type_pc = t1.code_type_pc AND CURRENT_DATE BETWEEN t2.start_date AND t2.end_date)', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 9, 'Refresh materialized view vmd_items_structures_features', 'refresh materialized view vmd_items_structures_features', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 10, 'Prezzo con marginalita'' aggiuntiva aggiornato', 'UPDATE tmd_sale_prices_var tspv SET price = fn_tmd_get_marg_price_from_percent(tis.id, tspv.vat_id, vfmil.network_id, 1, null, tspv.price, CAST((round(fn_tmd_get_marg_perc(tis.id, tspv.vat_id, vfmil.network_id, 1, null, tspv.price, null), 2) + vfmil.num_val) AS numeric)), update_date = now(), last_user = ''pr_last_operations'' FROM tmd_item_sales tis JOIN tmd_items ti ON tis.item_id = ti.id JOIN tin_data_item_in tdii ON tdii.item = ti.item JOIN vmd_feature_merchandise_item_links vfmil ON vfmil.item_id = ti.id JOIN tpa_specific_features tsf ON vfmil.specific_feature_id = tsf.id WHERE tspv.item_sale_id = tis.id AND tsf.specific_feature = ''MARGIN_ADD'' AND tspv.creation_date >= current_date AND tdii.creation_date::date = tspv.creation_date::date AND current_date BETWEEN tspv.start_date AND tspv.end_date AND fn_tmd_get_marg_price_from_percent(tis.id, tspv.vat_id, vfmil.network_id, 1, null, tspv.price, CAST((round(fn_tmd_get_marg_perc(tis.id, tspv.vat_id, vfmil.network_id, 1, null, tspv.price, null), 2) + vfmil.num_val) AS numeric))> 0', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', ''),
('3', 11, 'Procedura pr_management_table_date', 'call boom.pr_management_table_date()', '1', now(), now(), 'pr_last_operations', 'pr_last_operations', '');
