{
 "title": "DashBoard Caricamento DATI FORNITORI",
 "tags": [ "DASHFORNITORI" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vg_store",
    "label": "Negozio",
    "query": "select tn.network_code AS __value, \n       concat(tn.network_code,' - ',tn.description)  AS __text\nfrom   tmd_networks tn\nwhere tn.network_code in (select network_code from tin_data_third_party_in tdtpi  )\n--- Controllo utente\nand   ('${__user.login}' = 'admin'\n        or\n        ((tn.id in (select network_id from vpr_auth_user_networks vaun where lower(user_code) = '${__user.login}')\n         or\n         (select is_superuser from TPR_USERS where  lower(user_code) = '${__user.login}') = 1))\n    )    \norder by tn.network_code"
   },
   { "name": "vg_fase1", "label": "Fase 1", "query": "0,1,2" },
   { "name": "vg_fase2", "label": "Fase 2", "query": "0,1,2" },
   { "name": "vg_fase3", "label": "Fase 3", "query": "0,1,2" }
  ]
 },
 "panels": [
  {
   "title": "TOTALI ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     count(*) AS TOT_righe, \r\n   SUM( CASE WHEN processing_step1 <>0 THEN 1 END) AS FASE1_ELAB ,\r\n   SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  THEN 1 END) AS FASE2_ELAB,\r\n   SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  and processing_step3 <>0 THEN 1 END) AS FASE3_ELAB\r\n   --------SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  and processing_step3 <>0 and processing_step4 <>0THEN 1 END) AS FASE4_ELAB\r\n  --- count(distinct ITEM) AS TOT_ART, \r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE THEN item END) AS FLUSSOPH_ART,\r\n   -- COUNT(DISTINCT CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE THEN item END) AS FLUSSOEH_EAN,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE THEN item END) AS FLUSSOIH_INGR_ALLERG,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE THEN item END) AS FLUSSOFH_FORN,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%SH%' collate CASE_LIKE THEN item END) AS FLUSSOSH_ASSFORN\r\nFROM tin_data_third_party_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n AND (network_code IS NULL OR network_code IN ($vg_store));\r\n"
    }
   ]
  },
  {
   "title": "Flusso FH - Fornitori Nr.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    \r\n   COUNT(DISTINCT third_party||operational_agreement) AS FORNITORI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN third_party||operational_agreement END) AS FASE1_FILE_FORN ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN third_party||operational_agreement END) AS FASE2_ARRICHFILE_FORN,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN third_party||operational_agreement END) AS FASE3_CAR_BOOM_FORN\r\n  ----- COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_third_party_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n AND (network_code IS NULL OR network_code IN ($vg_store));"
    }
   ]
  },
  {
   "title": "Dettaglio Tabella di interfaccia FH",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT row_number() OVER(ORDER BY tdio.id)  nr_riga, \r\n   tdio.creation_date AS IL_data_creaz,\r\n    tdio.update_date AS IL_data_agg,\r\n    tdio.file_name AS IL_nome_file,\r\n    tdio.number_line AS IL_num_riga,\r\n    tdio.network_code AS IL_negozio,\r\n    tdio.processing_step1 AS IL_fase_1,\r\n    tdio.processing_step2 AS IL_fase_2,\r\n    tdio.processing_step3 AS IL_fase_3,\r\n   --- tdio.processing_step4 AS IL_fase_4,\r\n\ttdio.third_party as IL_forn,\r\n\ttdio.description as IL_descforn,\r\n\ttdio.business_name as IL_desclunga,\r\n    tdio.vat_number as IL_IVANUMB,\r\n    tdio.operational_agreement as IL_Accordo,\r\n    tdio.description_agreement as IL_DescAccordo, \r\n\t'* TAB_FORN *' as TAB_FORN,\r\n    ---tas.operational_agreement_id AS id_acc_oper_ges,\r\n    ttp.third_party as forn,\r\n    ttp.business_name as desc_forn,\r\n    tma.operational_agreement AS acc_oper,\r\n    tma.description AS desc_acc_oper,\r\n    '* DATI_INTERFACCIA *' as DATI_INTERFACCIA,\r\n    tdio.error_message AS IL_mess_err,\r\n    tdio.buffer_str as IL_buffer_dati\r\nFROM\r\n    tin_data_third_party_in tdio\r\nLEFT JOIN\r\n    tmd_networks tn ON tn.network_code = tdio.network_code\r\nLEFT JOIN\r\n    tmd_operational_agreements tma ON tma.operational_agreement = tdio.operational_agreement\r\nLEFT JOIN\r\n    tmd_third_parties ttp ON ttp.third_party = tdio.third_party\r\nWHERE\r\n    tdio.creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n----    AND (tdio.network_code IS NULL OR tdio.network_code IN ($vg_store))\r\n    AND tdio.processing_step1::text IN ($vg_fase1)\r\n    AND tdio.processing_step2::text IN ($vg_fase2)\r\n    AND tdio.processing_step3::text IN ($vg_fase3)\r\n   ----- AND tdio.processing_step4::text IN ($vg_fase4)\r\n AND (tdio.network_code IS NULL OR tdio.network_code IN ($vg_store))\r\n    order by   tdio.file_name ,\r\n    tdio.number_line ;"
    }
   ]
  }
 ]
}