{
 "title": "DashBoard Caricamento DATI ARTICOLO",
 "tags": [ "DASHARTICOLO" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "vg_store",
    "label": "Negozio",
    "query": "select tn.network_code AS __value, \n       concat(tn.network_code,' - ',tn.description)  AS __text\nfrom   tmd_networks tn\nwhere  network_node_type_pc = 4\nand    network_cash is not null\n--- Controllo utente\nand   ('${__user.login}' = 'admin'\n        or\n        ((tn.id in (select network_id from vpr_auth_user_networks vaun where lower(user_code) = '${__user.login}')\n         or\n         (select is_superuser from TPR_USERS where  lower(user_code) = '${__user.login}') = 1))\n    )    \norder by tn.network_code"
   },
   { "name": "vg_nomefile", "label": "Nome File " },
   { "name": "vg_codart", "label": "Cod.Art." },
   { "name": "vg_fase1", "label": "Fase 1", "query": "0,1,2" },
   { "name": "vg_fase2", "label": "Fase 2", "query": "0,1,2" },
   { "name": "vg_fase3", "label": "Fase 3", "query": "0,1,2" },
   { "name": "vg_fase4", "label": "Fase 4", "query": "0,1,2" }
  ]
 },
 "panels": [
  {
   "title": "TOTALI ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     count(*) AS TOT_righe, \r\n    SUM(CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE THEN 1 ELSE 0 END) AS FLUSSOPH_ART_RIGHE,\r\n   SUM(CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE  THEN 1 ELSE 0 END) AS FLUSSOEH_EAN_RIGHE,\r\n   SUM(CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE THEN 1 ELSE 0 END) AS FLUSSOIH_INGR_ALLERG_RIGHE,\r\n   SUM(CASE WHEN file_name LIKE '%FH%'collate CASE_LIKE THEN 1 ELSE 0 END) AS FLUSSOFH_FORN_RIGHE,\r\n   SUM(CASE WHEN file_name LIKE '%HH%' collate CASE_LIKE THEN 1 ELSE 0 END) AS FLUSSOHH_ASSFORN_RIGHE,\r\n   SUM( CASE WHEN processing_step1 <>0 THEN 1 END) AS FASE1_ELAB ,\r\n   SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  THEN 1 END) AS FASE2_ELAB,\r\n   SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  and processing_step3 <>0 THEN 1 END) AS FASE3_ELAB,\r\n   SUM( CASE WHEN processing_step1 <>0 and processing_step2 <>0  and processing_step3 <>0 and processing_step4 <>0THEN 1 END) AS FASE4_ELAB\r\n  --- count(distinct ITEM) AS TOT_ART, \r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE THEN item END) AS FLUSSOPH_ART,\r\n   -- COUNT(DISTINCT CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE THEN item END) AS FLUSSOEH_EAN,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE THEN item END) AS FLUSSOIH_INGR_ALLERG,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE THEN item END) AS FLUSSOFH_FORN,\r\n  --  COUNT(DISTINCT CASE WHEN file_name LIKE '%SH%' collate CASE_LIKE THEN item END) AS FLUSSOSH_ASSFORN\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FASE3 - DETTAGLIO FLUSS PH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     \r\n   SUM( CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1   THEN 1 END) AS PH_TOT,  \r\n      SUM( CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 not in(1,2) THEN 1 END) AS PH_DA_ELAB , \r\n   SUM( CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =1 THEN 1 END) AS PH_OK,  \r\n   SUM( CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =2 THEN 1 END) AS PH_KO\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Flusso PH - Articoli e Informazioni Anagrafiche",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    COUNT(*) AS PH_righe, \r\n   SUM(CASE WHEN processing_step1 = 1 THEN 1 ELSE 0 END) AS FASE1_FILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1 THEN 1 ELSE 0 END) AS FASE2_ARRICHFILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN 1 ELSE 0 END) AS FASE3_CAR_BOOM,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN 1 ELSE 0 END) AS FASE4_REGIA,\r\n   COUNT(DISTINCT item) AS PH_ARTICOLI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN item END) AS FASE1_FILE_ART ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN item END) AS FASE2_ARRICHFILE_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN item END) AS FASE3_CAR_BOOM_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND file_name LIKE '%PH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FASE3 - DETTAGLIO FLUSS EH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    \r\n   SUM( CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1   THEN 1 END) AS EH_TOT,  \r\n      SUM( CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 not in(1,2) THEN 1 END) AS EH_DA_ELAB , \r\n   SUM( CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =1 THEN 1 END) AS EH_OK,  \r\n   SUM( CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =2 THEN 1 END) AS EH_KO\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Flusso EH - EAN",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    COUNT(*) AS EH_righe, \r\n   SUM(CASE WHEN processing_step1 = 1 THEN 1 ELSE 0 END) AS FASE1_FILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1 THEN 1 ELSE 0 END) AS FASE2_ARRICHFILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN 1 ELSE 0 END) AS FASE3_CAR_BOOM,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN 1 ELSE 0 END) AS FASE4_REGIA,\r\n   COUNT(DISTINCT item) AS EH_ARTICOLI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN item END) AS FASE1_FILE_ART ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN item END) AS FASE2_ARRICHFILE_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN item END) AS FASE3_CAR_BOOM_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND file_name LIKE  '%EH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FASE3 - DETTAGLIO FLUSS IH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     \r\n   SUM( CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1   THEN 1 END) AS IH_TOT,  \r\n      SUM( CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 not in(1,2) THEN 1 END) AS IH_DA_ELAB , \r\n   SUM( CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =1 THEN 1 END) AS IH_OK,  \r\n   SUM( CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =2 THEN 1 END) AS IH_KO\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Flusso IH - INGREDIENTI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    COUNT(*) AS IH_righe, \r\n   SUM(CASE WHEN processing_step1 = 1 THEN 1 ELSE 0 END) AS FASE1_FILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1 THEN 1 ELSE 0 END) AS FASE2_ARRICHFILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN 1 ELSE 0 END) AS FASE3_CAR_BOOM,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN 1 ELSE 0 END) AS FASE4_REGIA,\r\n   COUNT(DISTINCT item) AS IH_ARTICOLI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN item END) AS FASE1_FILE_ART ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN item END) AS FASE2_ARRICHFILE_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN item END) AS FASE3_CAR_BOOM_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FASE3 - DETTAGLIO FLUSS FH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     \r\n   SUM( CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1   THEN 1 END) AS FH_TOT,  \r\n      SUM( CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 not in(1,2) THEN 1 END) AS FH_DA_ELAB , \r\n   SUM( CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =1 THEN 1 END) AS FH_OK,  \r\n   SUM( CASE WHEN file_name LIKE '%FH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =2 THEN 1 END) AS FH_KO\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%FH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Flusso FH - ASS FORN.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    COUNT(*) AS FH_righe, \r\n   SUM(CASE WHEN processing_step1 = 1 THEN 1 ELSE 0 END) AS FASE1_FILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1 THEN 1 ELSE 0 END) AS FASE2_ARRICHFILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN 1 ELSE 0 END) AS FASE3_CAR_BOOM,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN 1 ELSE 0 END) AS FASE4_REGIA,\r\n   COUNT(DISTINCT item) AS IH_ARTICOLI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN item END) AS FASE1_FILE_ART ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN item END) AS FASE2_ARRICHFILE_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN item END) AS FASE3_CAR_BOOM_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND file_name LIKE '%FH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FASE3 - DETTAGLIO FLUSS HH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    \r\n   SUM( CASE WHEN file_name LIKE '%HH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1   THEN 1 END) AS HH_TOT,  \r\n      SUM( CASE WHEN file_name LIKE '%HH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 not in(1,2) THEN 1 END) AS HH_DA_ELAB , \r\n   SUM( CASE WHEN file_name LIKE '%HH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =1 THEN 1 END) AS HH_OK,  \r\n   SUM( CASE WHEN file_name LIKE '%HH%' collate CASE_LIKE and processing_step1 =1 and processing_step2 =1  and processing_step3 =2 THEN 1 END) AS HH_KO\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%HH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Flusso HH -  Assortimenti",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    COUNT(*) AS HH_righe, \r\n   SUM(CASE WHEN processing_step1 = 1 THEN 1 ELSE 0 END) AS FASE1_FILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1 THEN 1 ELSE 0 END) AS FASE2_ARRICHFILE,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN 1 ELSE 0 END) AS FASE3_CAR_BOOM,\r\n   SUM(CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN 1 ELSE 0 END) AS FASE4_REGIA,\r\n   COUNT(DISTINCT item) AS IH_ARTICOLI,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 THEN item END) AS FASE1_FILE_ART ,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  THEN item END) AS FASE2_ARRICHFILE_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 THEN item END) AS FASE3_CAR_BOOM_ART,\r\n   COUNT(DISTINCT CASE WHEN processing_step1 = 1 and processing_step2 = 1  and processing_step3 = 1 and processing_step4 = 1 THEN item END) AS FASE4_REGIA_ART\r\nFROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND file_name LIKE '%HH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "Dettaglio Tabella di interfaccia PH, EH, IH, FH, SH",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT row_number() OVER(ORDER BY tdio.id)  nr_riga, \r\n   tdio.creation_date AS IL_data_creaz,\r\n    tdio.update_date AS IL_data_agg,\r\n    tdio.file_name AS IL_nome_file,\r\n    tdio.number_line AS IL_num_riga,\r\n    tdio.network AS IL_negozio,\r\n    tdio.processing_step1 AS IL_fase_1,\r\n    tdio.processing_step2 AS IL_fase_2,\r\n    tdio.processing_step3 AS IL_fase_3,\r\n    tdio.processing_step4 AS IL_fase_4,\r\n    tdio.item AS IL_articolo,\r\n    tdio.description_item AS IL_descrizione_articolo,\r\n\ttdio.structure_code as IL_strutt_merc,\r\n\ttdio.description_sale as IL_desc_vendita, \r\n\ttdio.sale_code as IL_ean,\r\n\ttdio.supplier_code||' - '||tdio.operational_agreement as IL_fornitore,\r\n\ttdio.purchase_price as IL_prz_acq,\r\n\ttdio.sale_price as IL_prz_vend,\r\n\t'* TAB_ART *' as TAB_ART,\r\n    ---ti.id AS id_art_ges,\r\n    ti.item AS articolo,\r\n    ttr.description AS desc_articolo,\r\n   -- ( SELECT tscv.sale_code\r\n   --        FROM tmd_sale_codes_var tscv\r\n   --       WHERE tscv.item_sale_id = tis.id AND CURRENT_DATE >= tscv.start_date AND CURRENT_DATE <= tscv.end_date AND tscv.code_type_pc = tdio.sale_code_type_pc\r\n    --     LIMIT 1) EAN,\r\n    ----vmd.structure_code AS cod_strutt_ges,\r\n   ----- vmd.description AS desc_strutt_ges,\r\n\t--'* TAB_FORN *' as TAB_FORN,\r\n    ---tas.operational_agreement_id AS id_acc_oper_ges,\r\n   -- ttp.third_party as forn,\r\n   -- ttp.business_name as desc_forn,\r\n   -- tma.operational_agreement AS acc_oper,\r\n   -- tma.description AS desc_acc_oper,\r\n--\t'* TAB_PRZ_ACQ *' as TAB_PRZ_ACQ,\r\n  --  tpp.price AS prz_acq,\r\n--\t'* TAB_PRZ_VEND *' as TAB_PRZ_VEND,\r\n ---   tsp.price AS prz_vend,\r\n    '* DATI_INTERFACCIA *' as DATI_INTERFACCIA,\r\n    tdio.error_message AS IL_mess_err,\r\n    tdio.buffer_str as IL_buffer_dati\r\nFROM\r\n    tin_data_item_in tdio\r\nLEFT JOIN\r\n    tmd_networks tn ON tn.network_code = tdio.network\r\nLEFT JOIN\r\n    tmd_items ti ON ti.item = tdio.item\r\nLEFT JOIN\r\n    ttr_items ttr ON ttr.item_id = ti.id AND ttr.language_id = 1\r\n--LEFT JOIN\r\n --   tmd_item_sales tis ON tis.item_id = ti.id AND tis.item_sale = 1\r\n--LEFT JOIN\r\n --   vmd_items_structures vmd ON vmd.item_id = ti.id\r\n --   AND vmd.merchandise_structure_id = 1\r\n  --  AND vmd.structure_level = 4\r\n--LEFT JOIN\r\n--    tmd_orderable_assortments tas ON tas.item_id = ti.id\r\n --   AND tas.network_id = tn.id\r\n  --  AND tas.main_supplier = 1\r\n  --  AND CURRENT_DATE BETWEEN tas.start_date AND tas.end_date\r\n--LEFT JOIN\r\n--    tmd_operational_agreements tma ON tma.id = tas.operational_agreement_id\r\n--LEFT JOIN\r\n --   tmd_third_parties ttp ON ttp.id = tma.third_party_id\r\n--LEFT JOIN\r\n --   tmd_purchase_prices tpp ON tpp.item_id = ti.id\r\n --   AND tpp.operational_agreement_id = tas.operational_agreement_id\r\n  --  AND tpp.network_id = tn.id\r\n   -- AND CURRENT_DATE BETWEEN tpp.start_date AND tpp.end_date\r\n--LEFT JOIN\r\n--    tmd_sale_prices tsp ON tsp.network_id = tn.id\r\n --   AND tsp.item_sale_id = tis.id\r\n --   AND CURRENT_DATE BETWEEN tsp.start_date AND tsp.end_date\r\nWHERE\r\n    tdio.creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n    AND (tdio.network IS NULL OR tdio.network IN ($vg_store))\r\n    AND tdio.processing_step1::text IN ($vg_fase1)\r\n    AND tdio.processing_step2::text IN ($vg_fase2)\r\n    AND tdio.processing_step3::text IN ($vg_fase3)\r\n    AND tdio.processing_step4::text IN ($vg_fase4)\r\nAND (\r\n  '$vg_codart' = '' \r\n  OR tdio.item like '$vg_codart' collate case_like\r\n)\r\nAND (\r\n  '$vg_nomefile' = '' \r\n  OR tdio.file_name like '$vg_nomefile' collate case_like\r\n)\r\n    order by   tdio.file_name ,\r\n    tdio.number_line ;"
    }
   ]
  }
 ]
}