{
 "title": "DashBoard Controlli Anagrafici",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Barcode multipli validi a parità di articolo",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  'tmd_sale_codes_var'tab, min(id) idmin ,max(id) idmax ,item_sale_id,network_id , code_type_pc, plu_code, tsc2.sale_code,count(*)\r\n    FROM tmd_sale_codes_var tsc2\r\n    WHERE current_date  between tsc2.start_date  and tsc2.end_date \r\n    group by  item_sale_id,network_id , code_type_pc, plu_code, tsc2.sale_code\r\n   having count(*) > 1\r\n   union\r\n   SELECT 'tmd_sale_codes'tab,  min(id) idmin ,max(id) idmax ,item_sale_id,network_id , code_type_pc, plu_code, tsc2.sale_code,count(*)\r\n    FROM tmd_sale_codes tsc2\r\n    WHERE current_date  between tsc2.start_date  and tsc2.end_date \r\n    group by  item_sale_id,network_id , code_type_pc, plu_code, tsc2.sale_code\r\n   having count(*) > 1\r\n"
    }
   ]
  },
  {
   "title": "Promozioni  in interfaccia non presenti su CAMPAIGN MANAGER",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select tsapvsite sito, tsapvndis promo , tsapvdescndis descr, tsapvtrt flg_trt, count(tsapvcexr) nr_art \r\nfrom tin_data_promotion_out tdpo \r\nwhere current_date between tsapvddeb and tsapvdfin \r\nand  not exists ( select 1 from boss.tesi_initiative where sz_host_id= tsapvndis)\r\ngroup by tsapvsite, tsapvndis , tsapvdescndis  , tsapvtrt"
    }
   ]
  },
  {
   "title": "Prezzi vendita multipli validi a parità di articolo",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT 'tmd_sale_prices_var' tab, min(tsc2.id) idmin ,max(tsc2.id) idmax ,ti.item, item_sale_id ,vat_id, network_id ,\r\n sale_price_type_pc,promo_code, count(*)\r\n    FROM tmd_sale_prices_var tsc2,\r\n        tmd_item_sales tis ,\r\n        tmd_items ti\r\n    WHERE current_date  between tsc2.start_date  and tsc2.end_date \r\n    and    tis.id = tsc2.item_sale_id\r\n     and ti.id = tis.item_id\r\n    group by  ti.item, item_sale_id ,vat_id, network_id,sale_price_type_pc,promo_code\r\n   having count(*) > 1    \r\n   union\r\n   SELECT 'tmd_sale_prices' tab, min(tsc2.id) idmin ,max(tsc2.id) idmax ,ti.item, item_sale_id ,vat_id, network_id ,\r\n sale_price_type_pc,promo_code, count(*)\r\n    FROM tmd_sale_prices tsc2,\r\n        tmd_item_sales tis ,\r\n        tmd_items ti\r\n    WHERE current_date  between tsc2.start_date  and tsc2.end_date \r\n    and    tis.id = tsc2.item_sale_id\r\n     and ti.id = tis.item_id\r\n    group by  ti.item, item_sale_id ,vat_id, network_id,sale_price_type_pc,promo_code\r\n   having count(*) > 1    "
    }
   ]
  },
  {
   "title": "Barcode validi in data su più articoli",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT 'tmd_sale_codes_var' tab, tsc2.network_id, tsc2.sale_code, tsc2.code_type_pc, count(*)\r\nFROM tmd_sale_codes_var tsc2\r\nWHERE current_date  between tsc2.start_date  and tsc2.end_date \r\ngroup by  tsc2.network_id, tsc2.sale_code, tsc2.code_type_pc\r\nhaving count(*) > 1\r\nunion\r\nSELECT 'tmd_sale_codes' tab,tsc2.network_id, tsc2.sale_code, tsc2.code_type_pc, count(*)\r\nFROM tmd_sale_codes tsc2\r\nWHERE current_date  between tsc2.start_date  and tsc2.end_date \r\ngroup by  tsc2.network_id, tsc2.sale_code, tsc2.code_type_pc\r\nhaving count(*) > 1"
    }
   ]
  },
  {
   "title": "Assortimenti multipli validi a parità di articolo stesso fornitore",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select 'tmd_orderable_assortments_var' tab, item_id,item_logistic_id,logistic_unit_id,operational_agreement_id, network_id ,count(*)\r\nfrom tmd_orderable_assortments_var toav where 1=1 \r\nand current_date between start_date and  end_date\r\ngroup  by item_id,item_logistic_id,logistic_unit_id,operational_agreement_id, network_id \r\nhaving count(*)>1\r\n   union\r\nselect 'tmd_orderable_assortments' tab, item_id,item_logistic_id,logistic_unit_id,operational_agreement_id, network_id ,count(*)\r\nfrom tmd_orderable_assortments toav where 1=1 \r\nand current_date between start_date and  end_date\r\ngroup  by item_id,item_logistic_id,logistic_unit_id,operational_agreement_id, network_id \r\nhaving count(*)>1\r\n\r\n   "
    }
   ]
  },
  {
   "title": "Barcode non validi da elaborare",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "select item,network_code,description,sale_code, to_char(start_date,'dd-mm-yyyy') start_Date,to_char(end_date,'dd-mm-yyyy') end_Date  \r\nfrom boom.tin_trace_sale_code_boss\r\nwhere end_date < current_Date \r\nand processing_status <> 1"
    }
   ]
  },
  {
   "title": "Potenziali problemi gestione in data - Se maggiore di zero da verificare ",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select 'tmd_orderable_assortments_var' tab, count(*) conta from tmd_orderable_assortments_var tppv    where end_date < start_date \r\nunion\r\nselect 'tmd_orderable_assortments' tab, count(*) conta from tmd_orderable_assortments tppv    where end_date < start_date \r\nunion\r\nselect 'tmd_purchase_prices_var' tab, count(*) conta from tmd_purchase_prices_var tppv    where end_date < start_date \r\nunion\r\nselect 'tmd_purchase_prices' tab, count(*) conta from tmd_purchase_prices tspv  where end_date < start_date \r\nunion\r\nselect 'tmd_sale_prices_var' tab, count(*) conta from tmd_sale_prices_var tspv  where end_date < start_date \r\nunion\r\nselect 'tmd_sale_prices' tab, count(*) conta from tmd_sale_prices tspv  where end_date < start_date \r\nunion\r\nselect 'tmd_sale_codes_var' tab, count(*) conta from tmd_sale_codes_var tspv  where end_date < start_date \r\nunion\r\nselect 'tmd_sale_codes' tab, count(*) conta from tmd_sale_codes tspv  where end_date < start_date \r\n   "
    }
   ]
  }
 ]
}