{
 "title": "DashBoard Caricamento DATI - GENERALE",
 "tags": [ "DASHGEN" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "vg_store",
    "label": "Negozio",
    "query": "select tn.network_code AS __value, \n       concat(tn.network_code,' - ',tn.description)  AS __text\nfrom   tmd_networks tn\nwhere  network_node_type_pc = 4\nand    network_cash is not null\n--- Controllo utente\nand   ('${__user.login}' = 'admin'\n        or\n        ((tn.id in (select network_id from vpr_auth_user_networks vaun where lower(user_code) = '${__user.login}')\n         or\n         (select is_superuser from TPR_USERS where  lower(user_code) = '${__user.login}') = 1))\n    )    \norder by tn.network_code"
   },
   { "name": "URL", "label": "URL" }
  ]
 },
 "panels": [
  {
   "title": "ARTICOLI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT     count(*) AS TOT_righe, \r\n    SUM(CASE WHEN file_name LIKE '%PH%' collate CASE_LIKE THEN 1 ELSE 0 END) AS ARTICOLI,\r\n   SUM(CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE  THEN 1 ELSE 0 END) AS BARCODE,\r\n   SUM(CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE THEN 1 ELSE 0 END) AS INGReALLERG\r\n FROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "KIT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM  tin_data_KIT_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  ---AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "PROMOZIONI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM  tin_data_promotion_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "FORNITORI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM tin_data_third_party_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  ---AND (network IS NULL OR network IN ($vg_store));\r\n\r\n"
    }
   ]
  },
  {
   "title": "ARTICOLI OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT    SUM(CASE WHEN PROCESSING_STEP3 = 1 THEN 1 ELSE 0 END) AS TOTALE_righe, \r\n    SUM(CASE WHEN file_name LIKE '%PH%'collate CASE_LIKE  AND PROCESSING_STEP3 = 1 THEN 1 ELSE 0 END) AS ARTICOLI,\r\n   SUM(CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE  AND PROCESSING_STEP3 = 1 THEN 1 ELSE 0 END) AS BARCODE,\r\n   SUM(CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE AND PROCESSING_STEP3 = 1 THEN 1 ELSE 0 END) AS INGReALLERG\r\n FROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n"
    }
   ]
  },
  {
   "title": "KIT OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM  tin_data_KIT_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  and processing_step3 = 1 ;\r\n\r\n"
    }
   ]
  },
  {
   "title": "PROMOZIONI OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM  tin_data_promotion_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store))\r\n  and processing_step4 = 1 and processing_promotion = 1;\r\n\r\n"
    }
   ]
  },
  {
   "title": "FONITORI OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM tin_data_third_party_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  ---AND (network IS NULL OR network IN ($vg_store));\r\n  and processing_step3 = 1 and processing_supplier = 1;\r\n\r\n"
    }
   ]
  },
  {
   "title": "ARTICOLI KO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT        SUM(CASE WHEN PROCESSING_STEP3 <> 1 THEN 1 ELSE 0 END) AS TOTALE_righe, \r\n    SUM(CASE WHEN file_name LIKE '%PH%'collate CASE_LIKE  AND PROCESSING_STEP3 <> 1 THEN 1 ELSE 0 END) AS ARTICOLI,\r\n   SUM(CASE WHEN file_name LIKE '%EH%' collate CASE_LIKE  AND PROCESSING_STEP3 <> 1 THEN 1 ELSE 0 END) AS BARCODE,\r\n   SUM(CASE WHEN file_name LIKE '%IH%' collate CASE_LIKE AND PROCESSING_STEP3 <> 1 THEN 1 ELSE 0 END) AS INGReALLERG\r\n FROM tin_data_item_in\r\nWHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store));\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "KIT KO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) totale\r\n  FROM  tin_data_KIT_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  and processing_step3 <> 1 ;"
    }
   ]
  },
  {
   "title": "PROMOZIONI KO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM  tin_data_promotion_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  AND (network IS NULL OR network IN ($vg_store))\r\n  and (processing_step4 <> 1 or processing_promotion <> 1);\r\n\r\n"
    }
   ]
  },
  {
   "title": "FORNITORI KO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT COUNT(*) totale\r\n  FROM tin_data_third_party_in\r\n    --WHERE creation_date between '${__from:date::timestamp without time zone}' and '${__to:date::timestamp without time zone}'\r\n    WHERE creation_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  ----AND file_name LIKE '%IH%' COLLATE CASE_LIKE\r\n  ---AND (network IS NULL OR network IN ($vg_store));\r\n  and (processing_step3 <> 1 OR processing_supplier <> 1);\r\n"
    }
   ]
  }
 ]
}